### ISSUE TITLE
Load plugin, parsing issues

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#100]
A new bugs for you, with @load plugin:

1) In load url no alias values are accepted, for example:
@load url($modulePath/foo.cssp)

2) If load plugin import another cssp file, you have to process this file like as the main cssp, because if in the loaded file i use a constant declared in the main cssp, this not works :(

general.cssp
@constants
    $imagePath: ../images

loaded.cssp
div#foo
    background: url($imagePath/bar.png)

Please fix it soon :(

**Comment by SirPepe** [comment]
Interesting... this really seems to be a problem. Didn't expect that. Looking at it.

**Comment by f-liva** [comment]
This means talking! I wait impatiently news ;)

**Comment by SirPepe** [comment]
Forget it, it's **NOT** a bug. The problem is that you're prefixing the constant with `$` in the `@constants` block, which is not correct. _Only use the `$` when using the constant, not when declaring it._ Incorrect:

```
@constants
    $imagePath: ../images
```

Correct:

```
@constants
    imagePath: ../images
```

**Comment by f-liva** [comment]
Yes yes i have writed all correct, i have wrong in this post but in my cssp the syntax is equals to your ;)

**Comment by SirPepe** [comment]
This is my test case, which works for me:

test1.cssp:

```
@turbine
    plugins:load
@constants
    imagePath: ../images
@load url($_FILEPATH/test2.cssp)
```

test2.cssp:

```
div#foo
    background: url($imagePath/bar.png)
```

Result:

```
div#foo {
    background: url(../images/bar.png);
}
```

**Comment by f-liva** [comment]
Hmm, now it works.. sorry and thanks!
