### ISSUE TITLE
Concatenaed selectors IE BUG

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#104]
So guys, this code works:

```
div:last-child
    width: 50%
div.last-child
    width: 50%
```

But with this syntac the css not write the selector with the class:

```
div:last-child, div.last-child
    width: 50%
```

What is it this issue? :(

**Comment by f-liva** [comment]
A precisation... Only with IE.
No problem for other browsers!

**Comment by SirPepe** [comment]
What's the css output you get? Selector generation should be browser-independent...

**Comment by f-liva** [comment]
I don't know, in IE the second selector is not writed in css :/

**Comment by SirPepe** [comment]
Can't reproduce this. Can you mail me the cssp file where this happens for you?

**Comment by f-liva** [comment]
I have just send you an email :)

**Comment by SirPepe** [comment]
Whitspace mishap, not a bug.
