### ISSUE TITLE
Syntax Highlighting for Coda

### ISSUE THREAD

**Issue by ghost** [TurbineCSS/Turbine#111]
Hello folks!

I really love turbine so far, but the lack of syntax highlighting for Coda is making my work hard. I already tried creating it myself, but wasn't successful. So I'm wondering if you can help me. You can find help over here:
http://www.codingmonkeys.de/subethaedit/mode.html (coda uses subethaedit's syntax highlighting so it will be working for all subethaedit users out there too)
http://pradador.com/code/coda/wordpressmode/ (Wordpress syntax coloring mode)

Thank you and keep up the good work! :)

**Comment by ghost** [comment]
Nevermind

I figured it out. Here is what I came up with:
<a href="http://webdevkit.net/2010/08/turbine-syntax-highlight-mode-for-coda/">http://webdevkit.net/2010/08/turbine-syntax-highlight-mode-for-coda/</a>

I realize it isn't perfect but its a start... :)

**Comment by SirPepe** [comment]
That's great! Let me know when you think it's good enough for the general public, i'd love to include this in Turbine.

**Comment by gnutix** [comment]
Is there a syntax highlighting plugin for Notepad++ ?

**Comment by SirPepe** [comment]
Not yet. Write one!

**Comment by SirPepe** [comment]
https://github.com/SirPepe/Turbine/issues#issue/138
