### ISSUE TITLE
@plugins list fails when ending on ;

### ISSUE THREAD

**Issue by Schepp** [TurbineCSS/Turbine#115]
While our property-declarations can end on a semicolon, the @plugins-list cannot (it then searches for a plugin with a ";" at the end of its name).
I like the possibility of ending lines on a semicolon as I my hands are still quite "hardwired" to CSS syntax. So I would like to be able to use that in all @-declarations as well.

**Comment by SirPepe** [comment]
Fixed in 9602dc3b859b77171e98902c26b254eb9b800b82, will be in 1.0.10

**Comment by SirPepe** [comment]
Fixed in 1.0.10
