### ISSUE TITLE
::selection

### ISSUE THREAD

**Issue by man-oi** [TurbineCSS/Turbine#117]
when trying to use *::selection, it dont parsed correctly:

```
*
    margin: 0
    padding: 0
    border: none
    *::selection
        color: #fff
        background: 000

    *::-moz-selection
        color: #fff
        background: 000
```

turns into

```
* {
    margin: 0;
    padding: 0;
    border: none;
    *: :-moz-selection;
    color: #fff;
    background: 000;
}
```

**Comment by SirPepe** [comment]
Confirmed, will be fixed in 1.0.11

**Comment by SirPepe** [comment]
Wait, not confirmed at all. For me the output is:

```
* {
    margin: 0;
    padding: 0;
    border: none;
}
* *::selection {
    color: #fff;
    background: 000;
}
* *::-moz-selection {
    color: #fff;
    background: 000;
}
```

...which is what i would expect. Hm... which version are you using?

**Comment by man-oi** [comment]
ok i see it is use for comments in turbine. (edit: oh no, only for developing, shame) and ist also only css3 and not yet defined: http://www.w3.org/TR/css3-selectors/#selection but i think, it were great to use that also in turbine. Otherwise for the moment i write a little css snippet and add it to the get files variable, thats ok for the moment i think.

**Comment by man-oi** [comment]
the newest version i used today, 1.0.10

btw for the first time, and without that, its a great work! thanks!

**Comment by SirPepe** [comment]
Turned out not to be a bug but a whitespace mishap.
