### ISSUE TITLE
Suggestion for minifier

### ISSUE THREAD

**Issue by SimonWpt** [TurbineCSS/Turbine#121]
I have some minor suggestions for the minifier:
1. shorthand support for font-weight:
   normal =400
   bold=700
2. remove useless whitespace
   a{color:red&nbsp;&nbsp;&nbsp;&nbsp;!important}

**Comment by SirPepe** [comment]
Good ideas for 1.1.0

**Comment by SirPepe** [comment]
Implemented in dev, will definitly be in 1.1.0

**Comment by gnutix** [comment]
I also have a suggestion for the minifier. Why not use the YUI Compressor's CSS ( http://developer.yahoo.com/yui/compressor/css.html ) ? It's probably the best public script for CSS compressing available! ;)

But it has been written in Java, with just have a port for Javascript. Don't know if it really fits in the project idea...

Another wonderful CSS compressor I found is CleanCSS ( http://www.cleancss.com/ ), that use CSSTidy ( http://csstidy.sourceforge.net/ ).

**Comment by SirPepe** [comment]
These won't work for Turbine (or at least the Minifier) - the minifier doesn't process raw CSS, but optimizes the values of the data tree after parsing. One could of course write a completely new plugin that runs on the before_output hook and that uses YUI or CSSTidy, but I doubt it's worth the effort.
