### ISSUE TITLE
background-gradient and colorsmodels module is not working together for IE background in RGBA

### ISSUE THREAD

**Issue by TomaszJanusz** [TurbineCSS/Turbine#127]
When both modules is active and browser is IE is not available to set background color in RGBA. Turbine for: 

background:rgba(200, 0, 0, 0.5)

creates: 
progid:DXImageTransform.Microsoft.gradient(enabled:false) // code is generated by background-gradient module. why? i don't know

and when i disable this module:
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#80C80000,endColorstr=#80C80000); // this is from colormodels

**Comment by SirPepe** [comment]
This happens because in 1.0.X there's no central color calculation class that plugins can use, so each plugin handels colors by itself (and not very good). The problem is already solved in 1.1.0 but until it's stable I'm afraid you'll have to use hex colors.

**Comment by TomaszJanusz** [comment]
I just simple disable gradient plugin in css3 meta plugin :-)
