### ISSUE TITLE
Syntax Highlighting for Notepad++

### ISSUE THREAD

**Issue by Zae** [TurbineCSS/Turbine#130]
Would it be possible to create a language file for use with Notepad++?

http://sourceforge.net/apps/mediawiki/notepad-plus/index.php?title=User_Defined_Language_Files

**Comment by SirPepe** [comment]
I don't see why this should be impossible :) But I don't use Notepad++ (I don't even use Windows) so I probably won't write a language file for it. If you do it I'll be happy to make it an offical part of Turbine.

**Comment by SirPepe** [comment]
https://github.com/SirPepe/Turbine/issues#issue/138
