### ISSUE TITLE
make linear-gradient use data-uri's for opera

### ISSUE THREAD

**Issue by commi** [TurbineCSS/Turbine#150]
instead of using the external svg.php just capture its output and url-encode it (or base64-encode, not sure which would be smaller/more compressible) and put it in the css.

**Comment by radex** [comment]
Yes! Please implement. SVG doesn't weigh too much and one file less to download is always a good thing...

**Comment by SirPepe** [comment]
One less download is indeed always a good thing, but saving one single file for one single browser with a rather small market share isn't my highest priority now. But if someone can provide an implementation for this, i'll gladly itegrate it,

**Comment by commi** [comment]
i finally installed git and implemented this im my fork (commi/Turbine). simpler than expected. base64-encoding seems to be necessary for opera to parse data-uris in css
