### ISSUE TITLE
Implement class extender and generated selectors

### ISSUE THREAD

**Issue by SirPepe** [TurbineCSS/Turbine#40]
ul
    li
      &+ li
        background: red

.. where `&` references the parent element (in this case `li`). But we need a better name.

**Comment by MadeMyDay** [comment]
Change line 49:

```
$cssp->insert($changed,'global',$selector);
```

to

```
$cssp->insert($changed,$block,$selector);
```

otherwise changed properties are not inserted in the correct block (if you have more than one, e.g. media queries).

**Comment by SirPepe** [comment]
Mostly implemented. This works so far:

```
#foo
    &.bar
        color:red

#bar
    &.foo, &.asdf
        color:green

#bar, #baz
    &.foo, &.asdf
        &:whatever
            color:green

a(:hover, :active, #foo, .whatever)
    color:blue

div.post-(1-10)
    color:yellow
```

Combinations of `&`-selectors and generated selectors don't:

```
#bar
    &.post-(1-10)
        color:pink

div.post-(1-10)-
    &bar
        color:magenta
```

**Comment by SirPepe** [comment]
Should now work as planned
