### ISSUE TITLE
Alternative writing for multiple selectors

### ISSUE THREAD

**Issue by Schepp** [TurbineCSS/Turbine#42]
When I have multiple selectors in Turbine I need to write them into one single line, like this:

html,body
    margin: 0;
    padding: 0;
    background-color: #DBDDD2;

That's okay for just a few short selectors. But when I have a lot of selectors and/or longer selectros, it would help being able to write each one into a new line, like this:

html,
body
    margin: 0;
    padding: 0;
    background-color: #DBDDD2;

**Comment by SirPepe** [comment]
Implemented in the parser refactoring effort since 073ec8e796651a0c34a550c4a4e2f10d1b7df111
