### ISSUE TITLE
Browser class: Check for IE tester

### ISSUE THREAD

**Issue by SirPepe** [TurbineCSS/Turbine#48]

**Comment by Schepp** [comment]
IETester IE6 (auf Win7 x64):
Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.1; WOW64; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0) 

IETester IE7 (auf Win7 x64):
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)

**Comment by SirPepe** [comment]
Works!
