### ISSUE TITLE
fontface-plugin should support woff and find fonts by itself

### ISSUE THREAD

**Issue by Schepp** [TurbineCSS/Turbine#55]
why not having it that way, that one has to code just this:

@font-face
      font-family:'Graublau Web';
      src:url(font/GraublauWeb);

and then the plugin checks automatically for font/GraublauWeb.eot and font/GraublauWeb.otf and font/GraublauWeb.ttf and font/GraublauWeb.woff?

**Comment by Schepp** [comment]
Or what if it makes use of browser-detection?

**Comment by SirPepe** [comment]
Fixed in 1f9d91d1c346eebb4d92e9775fdfe71b452d51ea
