### ISSUE TITLE
Add dimensions plugin

### ISSUE THREAD

**Issue by SirPepe** [TurbineCSS/Turbine#65]
Lets you use

```
dimensions: 200px 12em
```

instead of

```
height: 200px
width:12em
```

**Comment by SimonWpt** [comment]
IMHO we should use singular instead of plural for elements, attributes and properties? So "dimension" is the better attribute-name.

**Comment by SirPepe** [comment]
I'm not even sure we need this thing. A whole new plugin ony for this litte "problem" is a bit overkill.

**Comment by SirPepe** [comment]
If anyone wants to do this, this would be something for http://github.com/SirPepe/Turbine-Extras but not for the main project.
