### ISSUE TITLE
When constructing the -ms-filter property, check for double "

### ISSUE THREAD

**Issue by Schepp** [TurbineCSS/Turbine#78]
Sometimes a -ms-filter: ""progid:..."" is created because the filter-value itself already bears " and Turbine puts this again inside ", in the end doubling the " and disabling the filter. We should filter out double quotes, e.g. with a t_rim($filter,'"')_ or a _str_replace('""','"',$filter)_.

**Comment by SirPepe** [comment]
Fixed in eb0ed313ad9bcc0d2686
