### ISSUE TITLE
Allow remote cssp files via http

### ISSUE THREAD

**Issue by Traxmaxx** [TurbineCSS/Turbine#79]
Allow Turbine to parse remote cssp files via http, for working with a single Turbine installation on multiple projects.

**Comment by Schepp** [comment]
That would be a very bad idea for performance as we do a filetime-check on each css.php-call to find out if our source-files were updated. If not we send a 304, if yes we do all the expensive parsing. This file-check is quick on the local filesystem but is not practical with remote resources.

If all your projects are on the same machine you could try some modrewrite action. Just a quick idea that came up my mind - without any deeper thoughts.
