### ISSUE TITLE
Images relative to Turbine directory instead of relative to css_base_dir.

### ISSUE THREAD

**Issue by MadeMyDay** [TurbineCSS/Turbine#82]
1.0.2: 

background:url(images/icons.png) top left no-repeat

looks in turbine/images/ instead of

'css_base_dir' => '../css/',

=> ../css/images/

**Comment by SirPepe** [comment]
No really a bug since css_base_dir is only meant to be used for for the parameters of css.php. But maybe an image_base_dir would be a useful new feature?

**Comment by MadeMyDay** [comment]
Yes, I think it would be useful. I just handled it with a constant, that`s fine, too.

**Comment by Schepp** [comment]
I would rather call it resources_base_dir, as it may encorporate fonts and htcs and so on.

But from my experience with Booster it might just make sense to take $_SERVER['DOCUMENT_ROOT'] as relative path base.

**Comment by SirPepe** [comment]
Not a priority at the moment - constants will have to suffice.
