### ISSUE TITLE
Pseudo-classes 

### ISSUE THREAD

**Issue by MadeMyDay** [TurbineCSS/Turbine#84]
It would be cool to have an input like this:

```
li.item
    background: blue
    :hover
        background: red
```

would become
    li.item{
    background: blue;
    }
    li.item:hover{
    background: red;
    }

**Comment by SirPepe** [comment]
http://github.com/Traxmaxx/Turbine/blob/master/plugins/classextender.php

Will be in 1.1.0

**Comment by MadeMyDay** [comment]
That is not the same. With the plugin the output also is

```
li.item :hover{
background: red;
}
```

That doesn`t make sense from my point of view. Why not parse for ":" at the beginning of new selectors and put it directly behind the preceding one? 

Edit: Okay, makes sense. A #foo :hover for hovering all elements in #foo really is possible.

With the plugin it looks like:

li.item
    background: blue
    &:hover
        background: red

which works also well.
