### ISSUE TITLE
Directory traversal vulnerability

### ISSUE THREAD

**Issue by K14D** [TurbineCSS/Turbine#86]
It's possible to let Turbine parse files outside the configured directory (i.e. ...turbine/css.php?files=../../whatever.file). In most cases the resulting output is empty, because the parser doesn't find anything useful.
Parser2::load_file should check for dangerous paths in $file.

**Comment by SirPepe** [comment]
Maybe add a option to config.php where a list of safe directories can be defined

**Comment by K14D** [comment]
Ignoring paths with "../" would be a start.

**Comment by SirPepe** [comment]
Fixed in 1.0.5
