### ISSUE TITLE
image creation

### ISSUE THREAD

**Issue by SimonWpt** [TurbineCSS/Turbine#88]
I have often projects, where I have to use simple graphics (i.e. backgrounds for menu). Look at my blogentry for more infos: http://simonwpt.blogspot.com/2010/01/svg-vektorgrafik-mit.html

It would be great, if turbine could create such graphics (png not svg :-) ).

**Comment by SirPepe** [comment]
Can you post an example how this would work in Turbine code?

**Comment by SimonWpt** [comment]
<pre>
@images
    url:$_FILEPATH/background.jpg
    dimension:800,600
    rect:0,0,800,300,#f00
    rect:0,300,800,300,#a00
    ellipse:400,300,100,100,#900
    url:$_FILEPATH/menu.jpg
    dimension:200,800
    rect:0,0,200,400,#f00
    rect:0,400,200,800,#a00

body
    background:#fff url("$_FILEPATH/background.jpg") 50% 0 no-repeat
    div#nav
        background:#fff url("$_FILEPATH/menu.jpg") 0 0 no-repeat
</pre>
