### ISSUE TITLE
possibility to add { }

### ISSUE THREAD

**Issue by ogorzalka** [TurbineCSS/Turbine#90]
I think it would be great to have the possibility to use braces instead of indentation. The new sass offer this possibility ;)

**Comment by SirPepe** [comment]
This would probably require quite a bit of parser rewriting... if somebody made a patch for this i would accept it happily but at the moment I think it would be better to simply use the CSS to Turbine converter (http://turbine.peterkroener.de/converter.php). This is a "wontfix" for now.
