### ISSUE TITLE
Internet Explorer multiple filters

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#93]
In Internet Explorer you can insert multiple "filter" property per CSS selector, but if i declare, in a cssp file, a box-shadow and a linear-gradient in the same selector Turbine overwrite the first with the second filter, instead of add both.

**Comment by f-liva** [comment]
A precisation: this bug is present only in IE8, instead IE7 has multiple filters.

**Comment by SirPepe** [comment]
The problem is that the comma between filters, which is mandatory in IE8 but not IE7, is missing. Confirmed and work in progress.

**Comment by f-liva** [comment]
Very good, i wait changes ;)

**Comment by SirPepe** [comment]
Fixed in 1.0.4

**Comment by f-liva** [comment]
Have you already fixed? Like as speedy gonzales :P
