### ISSUE TITLE
Linear gradient syntax issue

### ISSUE THREAD

**Issue by f-liva** [TurbineCSS/Turbine#95]
Another bug, linear gradient turbine property not support spaces between commas. Like this example:

linear-gradient(top,white,black) - WORKS
linear-gradient(top, white, black) - _NOT_ WORKS

**Comment by SirPepe** [comment]
Confirmed, will be fixed in 1.0.5

**Comment by SirPepe** [comment]
Fixed in 1.0.5

**Comment by f-liva** [comment]
Delicious :)
